# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc.user.v1 import user_pb2 as rpc_dot_user_dot_v1_dot_user__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rpc/user/v1/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserAuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/user.v1.UserAuthService/Register',
                request_serializer=rpc_dot_user_dot_v1_dot_user__pb2.RegisterRequest.SerializeToString,
                response_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/user.v1.UserAuthService/Login',
                request_serializer=rpc_dot_user_dot_v1_dot_user__pb2.LoginRequest.SerializeToString,
                response_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/user.v1.UserAuthService/Logout',
                request_serializer=rpc_dot_user_dot_v1_dot_user__pb2.LogoutRequest.SerializeToString,
                response_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.GetMe = channel.unary_unary(
                '/user.v1.UserAuthService/GetMe',
                request_serializer=rpc_dot_user_dot_v1_dot_user__pb2.GetMeRequest.SerializeToString,
                response_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.GetMeResponse.FromString,
                _registered_method=True)
        self.GetAdminDashboard = channel.unary_unary(
                '/user.v1.UserAuthService/GetAdminDashboard',
                request_serializer=rpc_dot_user_dot_v1_dot_user__pb2.GetAdminDashboardRequest.SerializeToString,
                response_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.GetAdminDashboardResponse.FromString,
                _registered_method=True)
        self.DispatchOrder = channel.unary_unary(
                '/user.v1.UserAuthService/DispatchOrder',
                request_serializer=rpc_dot_user_dot_v1_dot_user__pb2.DispatchOrderRequest.SerializeToString,
                response_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.DispatchOrderResponse.FromString,
                _registered_method=True)
        self.UpdateWorkerStatus = channel.unary_unary(
                '/user.v1.UserAuthService/UpdateWorkerStatus',
                request_serializer=rpc_dot_user_dot_v1_dot_user__pb2.UpdateWorkerStatusRequest.SerializeToString,
                response_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.UpdateWorkerStatusResponse.FromString,
                _registered_method=True)


class UserAuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdminDashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DispatchOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorkerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserAuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.RegisterRequest.FromString,
                    response_serializer=rpc_dot_user_dot_v1_dot_user__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.LoginRequest.FromString,
                    response_serializer=rpc_dot_user_dot_v1_dot_user__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.LogoutRequest.FromString,
                    response_serializer=rpc_dot_user_dot_v1_dot_user__pb2.LogoutResponse.SerializeToString,
            ),
            'GetMe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMe,
                    request_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.GetMeRequest.FromString,
                    response_serializer=rpc_dot_user_dot_v1_dot_user__pb2.GetMeResponse.SerializeToString,
            ),
            'GetAdminDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdminDashboard,
                    request_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.GetAdminDashboardRequest.FromString,
                    response_serializer=rpc_dot_user_dot_v1_dot_user__pb2.GetAdminDashboardResponse.SerializeToString,
            ),
            'DispatchOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchOrder,
                    request_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.DispatchOrderRequest.FromString,
                    response_serializer=rpc_dot_user_dot_v1_dot_user__pb2.DispatchOrderResponse.SerializeToString,
            ),
            'UpdateWorkerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkerStatus,
                    request_deserializer=rpc_dot_user_dot_v1_dot_user__pb2.UpdateWorkerStatusRequest.FromString,
                    response_serializer=rpc_dot_user_dot_v1_dot_user__pb2.UpdateWorkerStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.v1.UserAuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.v1.UserAuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserAuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserAuthService/Register',
            rpc_dot_user_dot_v1_dot_user__pb2.RegisterRequest.SerializeToString,
            rpc_dot_user_dot_v1_dot_user__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserAuthService/Login',
            rpc_dot_user_dot_v1_dot_user__pb2.LoginRequest.SerializeToString,
            rpc_dot_user_dot_v1_dot_user__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserAuthService/Logout',
            rpc_dot_user_dot_v1_dot_user__pb2.LogoutRequest.SerializeToString,
            rpc_dot_user_dot_v1_dot_user__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserAuthService/GetMe',
            rpc_dot_user_dot_v1_dot_user__pb2.GetMeRequest.SerializeToString,
            rpc_dot_user_dot_v1_dot_user__pb2.GetMeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdminDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserAuthService/GetAdminDashboard',
            rpc_dot_user_dot_v1_dot_user__pb2.GetAdminDashboardRequest.SerializeToString,
            rpc_dot_user_dot_v1_dot_user__pb2.GetAdminDashboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DispatchOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserAuthService/DispatchOrder',
            rpc_dot_user_dot_v1_dot_user__pb2.DispatchOrderRequest.SerializeToString,
            rpc_dot_user_dot_v1_dot_user__pb2.DispatchOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWorkerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserAuthService/UpdateWorkerStatus',
            rpc_dot_user_dot_v1_dot_user__pb2.UpdateWorkerStatusRequest.SerializeToString,
            rpc_dot_user_dot_v1_dot_user__pb2.UpdateWorkerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
